version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_USER: workflow
      POSTGRES_PASSWORD: workflow123
      POSTGRES_DB: workflow_engine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  api:
    build:
      context: .
      dockerfile: deployments/docker/Dockerfile.api
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://workflow:workflow123@postgres:5432/workflow_engine?sslmode=disable
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-secret-key-change-this
    depends_on:
      - postgres
      - redis
    volumes:
      - ./config:/app/config

  worker:
    build:
      context: .
      dockerfile: deployments/docker/Dockerfile.worker
    environment:
      DATABASE_URL: postgres://workflow:workflow123@postgres:5432/workflow_engine?sslmode=disable
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis
    deploy:
      replicas: 3

  frontend:
    build:
      context: ./web
      dockerfile: ../deployments/docker/Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  postgres_data:
